### ISSUE TITLE
Winch disapear in last factorio version

### ISSUE THREAD

**Issue by VortiK** [Suprcheese/Vehicle-Wagon#10]
Hello, 

Since last factorio version (0.16.29) the winch disapear when clicking a vehicule to load or a wagon to unload.

Never had any issue before.

![image](https://user-images.githubusercontent.com/23299769/37313685-9d62949c-2650-11e8-9575-c323e052b863.png)

**Comment by Suprcheese** [comment]
Thank you for the report; I am able to reproduce the issue and will start working on a fix.

**Comment by Suprcheese** [comment]
Fixed for next version: https://github.com/Suprcheese/Vehicle-Wagon/commit/d91979ce8b3e93f805c75ad23bc001382ec12cb6

**Comment by VortiK** [comment]
Confirmed fixed, thanks alot !
