### ISSUE TITLE
Crash when multiple players attempt simultaneous vehicle (un)loading

### ISSUE THREAD

**Issue by Suprcheese** [Suprcheese/Vehicle-Wagon#14]
Bug reported on forums: https://forums.factorio.com/viewtopic.php?p=364181#p364181

Need to try to reproduce.

**Comment by robot256** [comment]
Could this be related to the behavior I saw where starting a new load operation cancels one already in progress?  Seems like there might need to be a queue of loading/unloading wagons that all players add to.

**Comment by Suprcheese** [comment]
Deprecated support for this mod
