### ISSUE TITLE
Train Coupling

### ISSUE THREAD

**Issue by ichbestimmtnicht** [Suprcheese/Vehicle-Wagon#2]
There is currently no way to connect wagons via script, but fixing it by hand is simple: just hop into the wagon or locomotive and press the "Connect train" hotkey (G by default).

Does i understand it in the false way? Do you mean especially to fix it? Because there is a Nifty Maniac who inveted it.
https://github.com/NiftyManiac/factorio-train-coupler
,
,

**Comment by Suprcheese** [comment]
Yeah, with Factorio 0.15 that is no longer an issue.
