### ISSUE TITLE
Switch to cross-including Std Lib code instead of bundling it with the mod

### ISSUE THREAD

**Issue by Suprcheese** [Suprcheese/Vehicle-Wagon#21]
In Factorio 0.17, I believe it is now possible to set Std Lib as a required dependency and #include its code, rather than having to bundle it all in with this mod.

**Comment by SuperSandro2000** [comment]
eg Nexela does it with this mod https://mods.factorio.com/mod/PickerAtheneum/downloads

**Comment by Suprcheese** [comment]
Perfect example, thanks!
