### ISSUE TITLE
Crash on winch loading with Induction charging 1.3.3 

### ISSUE THREAD

**Issue by knowfear1337** [Suprcheese/Vehicle-Wagon#5]
i was happy to test out the change you made to allow vehicles to keep there charge 
but on winching the car on i get a crash, i just realised i dont know where the crash reports are saved but i'm sure i can figure it out if it would be helpful

**Comment by ST-DDT** [comment]
@knowfear1337 Does it happen with the latest version as well?
Please provide the error message for the crash.

**Comment by knowfear1337** [comment]
well i'm home for Christmas and dont have my PC [sad times] but i dont _think_ it happened last time i tried it but i'll try and remember to test when i get back to uni.
