### ISSUE TITLE
Vehicle Wagon 1.1.3 crashes on unloading if vehicle loaded in previous version

### ISSUE THREAD

**Issue by ja-ko** [Suprcheese/Vehicle-Wagon#6]
Hey,
Lately I'm getting the following error when trying to unload a vehicle:

```
  64.909 Error MainLoop.cpp:940: Exception at tick 30763215: Error while running event Vehicle Wagon::on_tick (ID 0)
__Vehicle Wagon__/control.lua:89: bad argument #1 to '__newindex' (number expected, got nil)
  64.909 Error ServerMultiplayerManager.cpp:94: MultiplayerManager failed: "Error while running event Vehicle Wagon::on_tick (ID 0)
__Vehicle Wagon__/control.lua:89: bad argument #1 to '__newindex' (number expected, got nil)"
```

I'm guessing that this is caused by loading the vehicle into the train before upgrading to version 1.1.2
Thus the energy is not saved and can't be restored. The issue could be resolved by simply adding a null-check to control.lua:89

Thanks a lot for providing this awesome mod and thanks for hopefully fixing this bug.

**Comment by Suprcheese** [comment]
Very good point! Fixed in [r45](https://github.com/Suprcheese/Vehicle-Wagon/commit/fa173034caa56d6c67ee27a51be9381490741f4d) -- thanks for the bug report!
