### ISSUE TITLE
Possible Incompatibility With Logistics Train Network

### ISSUE THREAD

**Issue by legendblade** [Suprcheese/Vehicle-Wagon#8]
User 'tanuki_san' reports in Vehicle Wagon and LTN discussion posts (https://mods.factorio.com/mods/Supercheese/Vehicle%20Wagon/discussion/22754 and https://mods.factorio.com/mods/Optera/LogisticTrainNetwork/discussion/22753) that Vehicle Wagon is causing Logistic-Train-Network (by @Yousei9 ) train stops to not accept input nor output information.

As tested with Vehicle Wagon 1.2.0 and LTN 1.6.1 (alongside a host of other mods), I cannot reproduce this issue as shown: https://gfycat.com/GroundedDecimalHorsechestnutleafminer

Waiting for more input (map download, blueprint, etc) from original user before investigating further.

**Comment by legendblade** [comment]
Closing for now, as no further information has been provided by the original user through the discussion board.

**Comment by 0ptera** [comment]
Vehicle Wagon 1.2.0 works fine with LTN 1.6.2 for me.

Winching simply switches a train from auto into manual due to re-creating the train causing LTN Stops to no longer output any signals. If you set a train back to auto after winching LTN will correctly output the updated composition.

**Comment by legendblade** [comment]
@Yousei9 good point - we should probably restore the train's manual_mode flag after recreating the wagon car.

Thanks for pointing that out.
